### PR TITLE
Convert to pure plugin2 so it can be consumed by other plugins.

### PR DESCRIPTION
**Pull request by SysPete**
Converting to pure plugin2 allows this plugin to be consumed by other plugins and I'd really like to use this plugin inside Dancer2::Plugin::Auth::Extensible so I can throw out the existing email mess that's in there.

### CODE REVIEW

**Comment by SysPete** [comment]
@ironcamel sorry for pinging but I need this for D2PAE. If you're happy with this PR I'd _really_ appreciate a new release. If you're happy with the change but have no time for release then perhaps you'd consider co-maint? Free beers can be claimed from me either here in MT (OK - a bit of a long trek I admit) or at any conf we might both be at. :wink:

**Comment by ironcamel** [comment]
@SysPete sure thing. I added you as a collaborator to this github repo and as a co-maint on PAUSE. Thanks for your contributions!

**Comment by ironcamel** [comment]
Feel free to push a new release to CPAN.

**Comment by SysPete** [comment]
PAUSE looks OK but I can't push to GH. I'll push to CPAN now and push release commit + tags to GH once that is working.

**Comment by ironcamel** [comment]
2016-11-17-120632_1015x388_scrot

**Comment by SysPete** [comment]
Bah. Was just me not realising that I had to accept the GH invite. Never seen one of those before. Thanks again!

**Pull request merged**
